name: Add demo APIs url and release

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Check out the repo and build demo.
        run: |
          git clone https://github.com/Redocly/redoc
          cd redoc
          echo npm install

          #- name: gh-pages
          #  run: |
          #    cd noahv
          #    #sed -i 's@/static/@/xadmin/static/@g' index.html
          #    echo noah.airdb.io > CNAME
          #    git init
          #    git config user.name "airdb-bot"
          #    git config user.email "airdb-bot@airdb.com"
          #    git add -A
          #    git commit -m "Auto Update by actions"
          #    git push --force "https://${{ secrets.GithubBotToken }}@github.com/${GITHUB_REPOSITORY}" master:gh-pages
